name: build
on:
  push:
#   push:
#       branches: [ main ]
#   pull_request:
#       branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: mnist_download
        run: sh ${{github.workspace}}/mnist_downloader.sh
        working-directory: ${{github.workspace}}/build/
      - name: test
        run: ctest
        working-directory: ${{github.workspace}}/build/tests
